# Pixi is a package management tool for developers.
# Before running a task, pixi ensures that all listed dependencies are installed first.
#
# Pixi is not required for rerun, but it is a convenient way to install the
# dependencies required for this example.
#
# https://prefix.dev/docs/pixi/overview
#
# Use `pixi task list` to list the available tasks,
# and `pixi run TASK` to run it (e.g. `pixi run run`).

[project]
name = "rerun_cpp_example_opencv_eigen"
authors = ["rerun.io <opensource@rerun.io>"]
channels = ["conda-forge"]
description = "Use the Rerun C++ SDK together with Eigen and OpenCV"
homepage = "https://rerun.io"
license = "MIT OR Apache-2.0"
platforms = ["linux-64", "osx-arm64", "osx-64", "win-64"]
readme = "README.md"
repository = "https://github.com/rerun-io/cpp-example-opencv-eigen"
version = "0.1.0"


[tasks]
# Note: extra CLI argument after `pixi run TASK` are passed to the task cmd.

prepare = "cmake -G Ninja -B build -S . -DCMAKE_BUILD_TYPE=Debug"
clean = { cmd = "rm -rf build bin CMakeFiles/" }
build = { cmd = "mkdir -p bin && cmake --build build --config Debug --target all", depends_on = [
    "prepare",
] }
run = { cmd = "build/rerun_ext_example", depends_on = ["build"] }


[dependencies]
# Build tools:
cmake = "3.27.6"
cxx-compiler = "1.6.0.*"
ninja = "1.11.1"

# Required by Rerun:
arrow-cpp = "13.0.0.*"

# Required by this example:
eigen = "3.4.0.*"
opencv = "4.8.1.*"
