on: [push, pull_request]

name: CI

jobs:
  pixi-build:
    name: "pixi build"
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - uses: prefix-dev/setup-pixi@v0.3.0
        with:
          pixi-version: v0.5.0
          cache: true
      - run: pixi run build
